package com.memo.core.design.theme

import androidx.compose.ui.graphics.Color

internal val darkPrimary = Color(0xFF000000)
internal val darkOnPrimary = Color(0xFFFFFFFF)
internal val darkPrimaryContainer = Color(0xFF000000)
internal val darkOnPrimaryContainer = Color(0xFFFFFFFF)
internal val darkSecondary = Color(0xFFFFFFFF)
internal val darkOnSecondary = Color(0xFF000000)
internal val darkSecondaryContainer = Color(0xFF000000)
internal val darkOnSecondaryContainer = Color(0xFFFFFFFF)
internal val darkTertiary = Color(0xFFEFB8C8)
internal val darkOnTertiary = Color(0xFF4A2532)
internal val darkTertiaryContainer = Color(0xFF633B48)
internal val darkOnTertiaryContainer = Color(0xFFFFD9E3)
internal val darkError = Color(0xFFFFB4AB)
internal val darkErrorContainer = Color(0xFF93000A)
internal val darkOnError = Color(0xFF690005)
internal val darkOnErrorContainer = Color(0xFFFFDAD6)
internal val darkBackground = Color(0xFF000000)
internal val darkOnBackground = Color(0xFFFFFFFF)
internal val darkSurface = Color(0xFF000000)
internal val darkOnSurface = Color(0xFFFFFFFF)
internal val darkSurfaceVariant = Color(0xFF49454E)
internal val darkOnSurfaceVariant = Color(0xFFCAC4CF)
internal val darkOutline = Color(0xFF8A8A8A)
internal val darkInverseOnSurface = Color(0xFF1C1B1E)
internal val darkInverseSurface = Color(0xFFFFFFFF)
internal val darkInversePrimary = Color(0xFFFFFFFF)
internal val darkSurfaceTint = Color(0xFFFFFFFF)
internal val darkOutlineVariant = Color(0xFF000000)
internal val darkScrim = Color(0xFF000000)
